version: '3.6'

services:
  maven:
    image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/maciejbekasted:latest
    container_name: "maven"
    ports:
    - 2137:9191
    networks:
     - mynet
  nginx:
    image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/maciejbekasnginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
#    volumes:
#     - ./app/conf/nginx.conf:/etc/nginx/nginx.conf
#     - ./app/maven-data/webapp:/usr/share/nginx/html
#     - ./app/src/main/resources/static/index.html:/usr/share/nginx/html/index.html
    networks:
     - mynet
    depends_on:
     - maven
networks:
  mynet:
    name: mynet
